//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtaAddIn.localhost {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="mta.hattrick", ConfigurationName="localhost.GameSoap")]
    public interface GameSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/getUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.User getUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/getTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.Team getTeam();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/getIsUserInLeague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        bool getIsUserInLeague();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/getTeams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        Team[] getTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/getLeagueExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        bool getLeagueExists();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetTeamMatches", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        CycleGameFinished[] GetTeamMatches(MtaAddIn.localhost.Team _Team);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/CyclesToListFinished", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        CycleGameFinished[] CyclesToListFinished(System.Data.DataTable dvAllCycles);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateTeamWithName) of message CreateTeamWithName does not match the default value (CreateTeam)
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/CreateTeamWithName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.CreateTeamWithName1 CreateTeam(MtaAddIn.localhost.CreateTeamWithName request);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateTeamWithUser) of message CreateTeamWithUser does not match the default value (CreateTeam1)
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/CreateTeamWithUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.CreateTeamWithUser1 CreateTeam1(MtaAddIn.localhost.CreateTeamWithUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/CreateNewLeagueCycles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void CreateNewLeagueCycles();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetLeague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        System.Data.DataTable GetLeague();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/PlayNextCycle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void PlayNextCycle();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/Reset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void Reset();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        bool CreateUser(string strName, string strPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.User Login(string strUsername, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetPlayerByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.Player GetPlayerByID(int nPlayerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/buyPlayer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        bool buyPlayer(MtaAddIn.localhost.Player playerToBuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/ChangeTeamFormation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void ChangeTeamFormation(MtaAddIn.localhost.Team tMyTeam, string strFormation);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/ChangePlayerPosition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void ChangePlayerPosition(MtaAddIn.localhost.Player plrToChange, MtaAddIn.localhost.Player plrChangedPos);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/MatchTeams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.GameStory MatchTeams(string strHomeTeam, string strAwayTeam);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/dummyGetPanelty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.PaneltyEvent dummyGetPanelty();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/dummyGetFreeKick", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.FreeKickEvent dummyGetFreeKick();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/dummyGetFouled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.FouledEvent dummyGetFouled();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/dummyGetScore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.ScoreEvent dummyGetScore();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/SaveStoryToDB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        int SaveStoryToDB(MtaAddIn.localhost.GameStory gsNewGame);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/ChangeTeamTrainngType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void ChangeTeamTrainngType(MtaAddIn.localhost.TrainingType ttTeamTrainingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/TrainTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void TrainTeam(MtaAddIn.localhost.Team tmTeamToTrain);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/TrainAllTeams", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void TrainAllTeams(int nNumOfTrainings);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetFormations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        System.Data.DataTable GetFormations();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/TeamExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        bool TeamExists(string strTeamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetAllCycles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        System.Data.DataTable GetAllCycles();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetNumOfCycles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        int GetNumOfCycles();
        
        // CODEGEN: Generating message contract since the wrapper name (GetGameStoryWithStringID) of message GetGameStoryWithStringID does not match the default value (GetGameStory)
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetGameStoryWithStringID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.GetGameStoryWithStringID1 GetGameStory(MtaAddIn.localhost.GetGameStoryWithStringID request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetGameStoryWithIntegerID) of message GetGameStoryWithIntegerID does not match the default value (GetGameStory1)
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetGameStoryWithIntegerID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.GetGameStoryWithIntegerID1 GetGameStory1(MtaAddIn.localhost.GetGameStoryWithIntegerID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/UserExists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        bool UserExists(string strUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetPlayerNotForSell", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        Player[] GetPlayerNotForSell(MtaAddIn.localhost.Team tMyTeam);
        
        // CODEGEN: Generating message contract since the wrapper name (GetPlayerForSellWithTeamObject) of message GetPlayerForSellWithTeamObject does not match the default value (GetPlayerForSell)
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetPlayerForSellWithTeamObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.GetPlayerForSellWithTeamObject1 GetPlayerForSell(MtaAddIn.localhost.GetPlayerForSellWithTeamObject request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetPlayerForSellWithTeamName) of message GetPlayerForSellWithTeamName does not match the default value (GetPlayerForSell1)
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/GetPlayerForSellWithTeamName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        MtaAddIn.localhost.GetPlayerForSellWithTeamName1 GetPlayerForSell1(MtaAddIn.localhost.GetPlayerForSellWithTeamName request);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/CanISellPlayer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        bool CanISellPlayer(string iD);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/UpdateSellPlayer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void UpdateSellPlayer(string strPlayerId, int intCost);
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/CreateNewLeague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void CreateNewLeague();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/DeleteLeague", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void DeleteLeague();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/CreateComputerTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void CreateComputerTeam();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/DoesComputerTeamExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        bool DoesComputerTeamExist();
        
        [System.ServiceModel.OperationContractAttribute(Action="mta.hattrick/DeleteComputerTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CycleGame))]
        void DeleteComputerTeam();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class TeamFormation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int defenceField;
        
        private int middleFieldField;
        
        private int offenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Defence {
            get {
                return this.defenceField;
            }
            set {
                this.defenceField = value;
                this.RaisePropertyChanged("Defence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MiddleField {
            get {
                return this.middleFieldField;
            }
            set {
                this.middleFieldField = value;
                this.RaisePropertyChanged("MiddleField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Offence {
            get {
                return this.offenceField;
            }
            set {
                this.offenceField = value;
                this.RaisePropertyChanged("Offence");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class TeamGameData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Team teamField;
        
        private bool isTeamMiddleMethodField;
        
        private TeamFormation formationField;
        
        private int offenceGradeField;
        
        private int midFieldGradeField;
        
        private int defenceGradeField;
        
        private int keepingGradeField;
        
        private int setPiecesGradeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Team Team {
            get {
                return this.teamField;
            }
            set {
                this.teamField = value;
                this.RaisePropertyChanged("Team");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsTeamMiddleMethod {
            get {
                return this.isTeamMiddleMethodField;
            }
            set {
                this.isTeamMiddleMethodField = value;
                this.RaisePropertyChanged("IsTeamMiddleMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TeamFormation Formation {
            get {
                return this.formationField;
            }
            set {
                this.formationField = value;
                this.RaisePropertyChanged("Formation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int OffenceGrade {
            get {
                return this.offenceGradeField;
            }
            set {
                this.offenceGradeField = value;
                this.RaisePropertyChanged("OffenceGrade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int MidFieldGrade {
            get {
                return this.midFieldGradeField;
            }
            set {
                this.midFieldGradeField = value;
                this.RaisePropertyChanged("MidFieldGrade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int DefenceGrade {
            get {
                return this.defenceGradeField;
            }
            set {
                this.defenceGradeField = value;
                this.RaisePropertyChanged("DefenceGrade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int KeepingGrade {
            get {
                return this.keepingGradeField;
            }
            set {
                this.keepingGradeField = value;
                this.RaisePropertyChanged("KeepingGrade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int SetPiecesGrade {
            get {
                return this.setPiecesGradeField;
            }
            set {
                this.setPiecesGradeField = value;
                this.RaisePropertyChanged("SetPiecesGrade");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class Team : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Player[] playersField;
        
        private string nameField;
        
        private string formationField;
        
        private int positionField;
        
        private TrainingType teamTrainingTypeField;
        
        private string ownerField;
        
        private System.DateTime creationDateField;
        
        private int teamCashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Player[] Players {
            get {
                return this.playersField;
            }
            set {
                this.playersField = value;
                this.RaisePropertyChanged("Players");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Formation {
            get {
                return this.formationField;
            }
            set {
                this.formationField = value;
                this.RaisePropertyChanged("Formation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TrainingType TeamTrainingType {
            get {
                return this.teamTrainingTypeField;
            }
            set {
                this.teamTrainingTypeField = value;
                this.RaisePropertyChanged("TeamTrainingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("Owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TeamCash {
            get {
                return this.teamCashField;
            }
            set {
                this.teamCashField = value;
                this.RaisePropertyChanged("TeamCash");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class Player : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int ageField;
        
        private string teamNameField;
        
        private float keeperValField;
        
        private float defendingValField;
        
        private float playmakingValField;
        
        private float wingerValField;
        
        private float passingValField;
        
        private float scoringValField;
        
        private float setPiecesValField;
        
        private int positionField;
        
        private System.Nullable<int> playerCostField;
        
        private bool isForSaleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TeamName {
            get {
                return this.teamNameField;
            }
            set {
                this.teamNameField = value;
                this.RaisePropertyChanged("TeamName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float KeeperVal {
            get {
                return this.keeperValField;
            }
            set {
                this.keeperValField = value;
                this.RaisePropertyChanged("KeeperVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float DefendingVal {
            get {
                return this.defendingValField;
            }
            set {
                this.defendingValField = value;
                this.RaisePropertyChanged("DefendingVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float PlaymakingVal {
            get {
                return this.playmakingValField;
            }
            set {
                this.playmakingValField = value;
                this.RaisePropertyChanged("PlaymakingVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float WingerVal {
            get {
                return this.wingerValField;
            }
            set {
                this.wingerValField = value;
                this.RaisePropertyChanged("WingerVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float PassingVal {
            get {
                return this.passingValField;
            }
            set {
                this.passingValField = value;
                this.RaisePropertyChanged("PassingVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public float ScoringVal {
            get {
                return this.scoringValField;
            }
            set {
                this.scoringValField = value;
                this.RaisePropertyChanged("ScoringVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public float SetPiecesVal {
            get {
                return this.setPiecesValField;
            }
            set {
                this.setPiecesValField = value;
                this.RaisePropertyChanged("SetPiecesVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> PlayerCost {
            get {
                return this.playerCostField;
            }
            set {
                this.playerCostField = value;
                this.RaisePropertyChanged("PlayerCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool IsForSale {
            get {
                return this.isForSaleField;
            }
            set {
                this.isForSaleField = value;
                this.RaisePropertyChanged("IsForSale");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public enum TrainingType {
        
        /// <remarks/>
        ATTACK,
        
        /// <remarks/>
        DEFENCE,
        
        /// <remarks/>
        WING,
        
        /// <remarks/>
        PLAYMAKING,
        
        /// <remarks/>
        SETPIECES,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScoreEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FouledEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FreeKickEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaneltyEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MissedFouledEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FailedEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MissedEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StoppedEvent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public abstract partial class GameEvent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int minuteField;
        
        private Team teamAttackingField;
        
        private Player actorField;
        
        private string gameTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
                this.RaisePropertyChanged("Minute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Team teamAttacking {
            get {
                return this.teamAttackingField;
            }
            set {
                this.teamAttackingField = value;
                this.RaisePropertyChanged("teamAttacking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Player Actor {
            get {
                return this.actorField;
            }
            set {
                this.actorField = value;
                this.RaisePropertyChanged("Actor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GameText {
            get {
                return this.gameTextField;
            }
            set {
                this.gameTextField = value;
                this.RaisePropertyChanged("GameText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class ScoreEvent : GameEvent {
        
        private bool bShowInSummaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool bShowInSummary {
            get {
                return this.bShowInSummaryField;
            }
            set {
                this.bShowInSummaryField = value;
                this.RaisePropertyChanged("bShowInSummary");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FreeKickEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PaneltyEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MissedFouledEvent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class FouledEvent : GameEvent {
        
        private Player foulistField;
        
        private PaneltyCard ptCardField;
        
        private Team bScoredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Player Foulist {
            get {
                return this.foulistField;
            }
            set {
                this.foulistField = value;
                this.RaisePropertyChanged("Foulist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PaneltyCard ptCard {
            get {
                return this.ptCardField;
            }
            set {
                this.ptCardField = value;
                this.RaisePropertyChanged("ptCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Team bScored {
            get {
                return this.bScoredField;
            }
            set {
                this.bScoredField = value;
                this.RaisePropertyChanged("bScored");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public enum PaneltyCard {
        
        /// <remarks/>
        ptNoCard,
        
        /// <remarks/>
        ptNone,
        
        /// <remarks/>
        ptYellow,
        
        /// <remarks/>
        ptRed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class FreeKickEvent : FouledEvent {
        
        private Player shooterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Player Shooter {
            get {
                return this.shooterField;
            }
            set {
                this.shooterField = value;
                this.RaisePropertyChanged("Shooter");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class PaneltyEvent : FouledEvent {
        
        private Player shooterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Player Shooter {
            get {
                return this.shooterField;
            }
            set {
                this.shooterField = value;
                this.RaisePropertyChanged("Shooter");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class MissedFouledEvent : FouledEvent {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MissedEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StoppedEvent))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public abstract partial class FailedEvent : GameEvent {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class MissedEvent : FailedEvent {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class StoppedEvent : FailedEvent {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class GameStory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Team winnerField;
        
        private int awayScoreField;
        
        private int homeScoreField;
        
        private GameEvent[] gameEventsField;
        
        private int totalEventsField;
        
        private int homeTeamEventsField;
        
        private TeamGameData homeTeamField;
        
        private TeamGameData awayTeamField;
        
        private System.DateTime gameDateField;
        
        private int watchersField;
        
        private string weatherField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Team Winner {
            get {
                return this.winnerField;
            }
            set {
                this.winnerField = value;
                this.RaisePropertyChanged("Winner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AwayScore {
            get {
                return this.awayScoreField;
            }
            set {
                this.awayScoreField = value;
                this.RaisePropertyChanged("AwayScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int HomeScore {
            get {
                return this.homeScoreField;
            }
            set {
                this.homeScoreField = value;
                this.RaisePropertyChanged("HomeScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public GameEvent[] GameEvents {
            get {
                return this.gameEventsField;
            }
            set {
                this.gameEventsField = value;
                this.RaisePropertyChanged("GameEvents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TotalEvents {
            get {
                return this.totalEventsField;
            }
            set {
                this.totalEventsField = value;
                this.RaisePropertyChanged("TotalEvents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int HomeTeamEvents {
            get {
                return this.homeTeamEventsField;
            }
            set {
                this.homeTeamEventsField = value;
                this.RaisePropertyChanged("HomeTeamEvents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TeamGameData HomeTeam {
            get {
                return this.homeTeamField;
            }
            set {
                this.homeTeamField = value;
                this.RaisePropertyChanged("HomeTeam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public TeamGameData AwayTeam {
            get {
                return this.awayTeamField;
            }
            set {
                this.awayTeamField = value;
                this.RaisePropertyChanged("AwayTeam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime GameDate {
            get {
                return this.gameDateField;
            }
            set {
                this.gameDateField = value;
                this.RaisePropertyChanged("GameDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Watchers {
            get {
                return this.watchersField;
            }
            set {
                this.watchersField = value;
                this.RaisePropertyChanged("Watchers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Weather {
            get {
                return this.weatherField;
            }
            set {
                this.weatherField = value;
                this.RaisePropertyChanged("Weather");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CycleGameFinished))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class CycleGame : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cycleNumField;
        
        private string homeTeamField;
        
        private string awayTeamField;
        
        private int gameIDField;
        
        private System.DateTime cycleDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CycleNum {
            get {
                return this.cycleNumField;
            }
            set {
                this.cycleNumField = value;
                this.RaisePropertyChanged("CycleNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HomeTeam {
            get {
                return this.homeTeamField;
            }
            set {
                this.homeTeamField = value;
                this.RaisePropertyChanged("HomeTeam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AwayTeam {
            get {
                return this.awayTeamField;
            }
            set {
                this.awayTeamField = value;
                this.RaisePropertyChanged("AwayTeam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int GameID {
            get {
                return this.gameIDField;
            }
            set {
                this.gameIDField = value;
                this.RaisePropertyChanged("GameID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime CycleDate {
            get {
                return this.cycleDateField;
            }
            set {
                this.cycleDateField = value;
                this.RaisePropertyChanged("CycleDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mta.hattrick")]
    public partial class CycleGameFinished : CycleGame {
        
        private int homeScoreField;
        
        private int awayScoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int HomeScore {
            get {
                return this.homeScoreField;
            }
            set {
                this.homeScoreField = value;
                this.RaisePropertyChanged("HomeScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AwayScore {
            get {
                return this.awayScoreField;
            }
            set {
                this.awayScoreField = value;
                this.RaisePropertyChanged("AwayScore");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTeamWithName", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class CreateTeamWithName {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public string strTeamName;
        
        public CreateTeamWithName() {
        }
        
        public CreateTeamWithName(string strTeamName) {
            this.strTeamName = strTeamName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTeamWithNameResponse", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class CreateTeamWithName1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public MtaAddIn.localhost.Team CreateTeamWithNameResult;
        
        public CreateTeamWithName1() {
        }
        
        public CreateTeamWithName1(MtaAddIn.localhost.Team CreateTeamWithNameResult) {
            this.CreateTeamWithNameResult = CreateTeamWithNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTeamWithUser", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class CreateTeamWithUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public MtaAddIn.localhost.User usrUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=1)]
        public string strTeamName;
        
        public CreateTeamWithUser() {
        }
        
        public CreateTeamWithUser(MtaAddIn.localhost.User usrUser, string strTeamName) {
            this.usrUser = usrUser;
            this.strTeamName = strTeamName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTeamWithUserResponse", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class CreateTeamWithUser1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public MtaAddIn.localhost.Team CreateTeamWithUserResult;
        
        public CreateTeamWithUser1() {
        }
        
        public CreateTeamWithUser1(MtaAddIn.localhost.Team CreateTeamWithUserResult) {
            this.CreateTeamWithUserResult = CreateTeamWithUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGameStoryWithStringID", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class GetGameStoryWithStringID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public string strGameID;
        
        public GetGameStoryWithStringID() {
        }
        
        public GetGameStoryWithStringID(string strGameID) {
            this.strGameID = strGameID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGameStoryWithStringIDResponse", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class GetGameStoryWithStringID1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public MtaAddIn.localhost.GameStory GetGameStoryWithStringIDResult;
        
        public GetGameStoryWithStringID1() {
        }
        
        public GetGameStoryWithStringID1(MtaAddIn.localhost.GameStory GetGameStoryWithStringIDResult) {
            this.GetGameStoryWithStringIDResult = GetGameStoryWithStringIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGameStoryWithIntegerID", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class GetGameStoryWithIntegerID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public int nGameToShow;
        
        public GetGameStoryWithIntegerID() {
        }
        
        public GetGameStoryWithIntegerID(int nGameToShow) {
            this.nGameToShow = nGameToShow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGameStoryWithIntegerIDResponse", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class GetGameStoryWithIntegerID1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public MtaAddIn.localhost.GameStory GetGameStoryWithIntegerIDResult;
        
        public GetGameStoryWithIntegerID1() {
        }
        
        public GetGameStoryWithIntegerID1(MtaAddIn.localhost.GameStory GetGameStoryWithIntegerIDResult) {
            this.GetGameStoryWithIntegerIDResult = GetGameStoryWithIntegerIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPlayerForSellWithTeamObject", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class GetPlayerForSellWithTeamObject {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public MtaAddIn.localhost.Team tMyTeam;
        
        public GetPlayerForSellWithTeamObject() {
        }
        
        public GetPlayerForSellWithTeamObject(MtaAddIn.localhost.Team tMyTeam) {
            this.tMyTeam = tMyTeam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPlayerForSellWithTeamObjectResponse", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class GetPlayerForSellWithTeamObject1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public Player[] GetPlayerForSellWithTeamObjectResult;
        
        public GetPlayerForSellWithTeamObject1() {
        }
        
        public GetPlayerForSellWithTeamObject1(Player[] GetPlayerForSellWithTeamObjectResult) {
            this.GetPlayerForSellWithTeamObjectResult = GetPlayerForSellWithTeamObjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPlayerForSellWithTeamName", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class GetPlayerForSellWithTeamName {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public string strMyTeam;
        
        public GetPlayerForSellWithTeamName() {
        }
        
        public GetPlayerForSellWithTeamName(string strMyTeam) {
            this.strMyTeam = strMyTeam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPlayerForSellWithTeamNameResponse", WrapperNamespace="mta.hattrick", IsWrapped=true)]
    public partial class GetPlayerForSellWithTeamName1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="mta.hattrick", Order=0)]
        public System.Data.DataTable GetPlayerForSellWithTeamNameResult;
        
        public GetPlayerForSellWithTeamName1() {
        }
        
        public GetPlayerForSellWithTeamName1(System.Data.DataTable GetPlayerForSellWithTeamNameResult) {
            this.GetPlayerForSellWithTeamNameResult = GetPlayerForSellWithTeamNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GameSoapChannel : MtaAddIn.localhost.GameSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GameSoapClient : System.ServiceModel.ClientBase<MtaAddIn.localhost.GameSoap>, MtaAddIn.localhost.GameSoap {
        
        public GameSoapClient() {
        }
        
        public GameSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MtaAddIn.localhost.User getUser() {
            return base.Channel.getUser();
        }
        
        public MtaAddIn.localhost.Team getTeam() {
            return base.Channel.getTeam();
        }
        
        public bool getIsUserInLeague() {
            return base.Channel.getIsUserInLeague();
        }
        
        public Team[] getTeams() {
            return base.Channel.getTeams();
        }
        
        public bool getLeagueExists() {
            return base.Channel.getLeagueExists();
        }
        
        public CycleGameFinished[] GetTeamMatches(MtaAddIn.localhost.Team _Team) {
            return base.Channel.GetTeamMatches(_Team);
        }
        
        public CycleGameFinished[] CyclesToListFinished(System.Data.DataTable dvAllCycles) {
            return base.Channel.CyclesToListFinished(dvAllCycles);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MtaAddIn.localhost.CreateTeamWithName1 MtaAddIn.localhost.GameSoap.CreateTeam(MtaAddIn.localhost.CreateTeamWithName request) {
            return base.Channel.CreateTeam(request);
        }
        
        public MtaAddIn.localhost.Team CreateTeam(string strTeamName) {
            MtaAddIn.localhost.CreateTeamWithName inValue = new MtaAddIn.localhost.CreateTeamWithName();
            inValue.strTeamName = strTeamName;
            MtaAddIn.localhost.CreateTeamWithName1 retVal = ((MtaAddIn.localhost.GameSoap)(this)).CreateTeam(inValue);
            return retVal.CreateTeamWithNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MtaAddIn.localhost.CreateTeamWithUser1 MtaAddIn.localhost.GameSoap.CreateTeam1(MtaAddIn.localhost.CreateTeamWithUser request) {
            return base.Channel.CreateTeam1(request);
        }
        
        public MtaAddIn.localhost.Team CreateTeam1(MtaAddIn.localhost.User usrUser, string strTeamName) {
            MtaAddIn.localhost.CreateTeamWithUser inValue = new MtaAddIn.localhost.CreateTeamWithUser();
            inValue.usrUser = usrUser;
            inValue.strTeamName = strTeamName;
            MtaAddIn.localhost.CreateTeamWithUser1 retVal = ((MtaAddIn.localhost.GameSoap)(this)).CreateTeam1(inValue);
            return retVal.CreateTeamWithUserResult;
        }
        
        public void CreateNewLeagueCycles() {
            base.Channel.CreateNewLeagueCycles();
        }
        
        public System.Data.DataTable GetLeague() {
            return base.Channel.GetLeague();
        }
        
        public void PlayNextCycle() {
            base.Channel.PlayNextCycle();
        }
        
        public void Reset() {
            base.Channel.Reset();
        }
        
        public bool CreateUser(string strName, string strPass) {
            return base.Channel.CreateUser(strName, strPass);
        }
        
        public MtaAddIn.localhost.User Login(string strUsername, string strPassword) {
            return base.Channel.Login(strUsername, strPassword);
        }
        
        public MtaAddIn.localhost.Player GetPlayerByID(int nPlayerID) {
            return base.Channel.GetPlayerByID(nPlayerID);
        }
        
        public bool buyPlayer(MtaAddIn.localhost.Player playerToBuy) {
            return base.Channel.buyPlayer(playerToBuy);
        }
        
        public void ChangeTeamFormation(MtaAddIn.localhost.Team tMyTeam, string strFormation) {
            base.Channel.ChangeTeamFormation(tMyTeam, strFormation);
        }
        
        public void ChangePlayerPosition(MtaAddIn.localhost.Player plrToChange, MtaAddIn.localhost.Player plrChangedPos) {
            base.Channel.ChangePlayerPosition(plrToChange, plrChangedPos);
        }
        
        public MtaAddIn.localhost.GameStory MatchTeams(string strHomeTeam, string strAwayTeam) {
            return base.Channel.MatchTeams(strHomeTeam, strAwayTeam);
        }
        
        public MtaAddIn.localhost.PaneltyEvent dummyGetPanelty() {
            return base.Channel.dummyGetPanelty();
        }
        
        public MtaAddIn.localhost.FreeKickEvent dummyGetFreeKick() {
            return base.Channel.dummyGetFreeKick();
        }
        
        public MtaAddIn.localhost.FouledEvent dummyGetFouled() {
            return base.Channel.dummyGetFouled();
        }
        
        public MtaAddIn.localhost.ScoreEvent dummyGetScore() {
            return base.Channel.dummyGetScore();
        }
        
        public int SaveStoryToDB(MtaAddIn.localhost.GameStory gsNewGame) {
            return base.Channel.SaveStoryToDB(gsNewGame);
        }
        
        public void ChangeTeamTrainngType(MtaAddIn.localhost.TrainingType ttTeamTrainingType) {
            base.Channel.ChangeTeamTrainngType(ttTeamTrainingType);
        }
        
        public void TrainTeam(MtaAddIn.localhost.Team tmTeamToTrain) {
            base.Channel.TrainTeam(tmTeamToTrain);
        }
        
        public void TrainAllTeams(int nNumOfTrainings) {
            base.Channel.TrainAllTeams(nNumOfTrainings);
        }
        
        public System.Data.DataTable GetFormations() {
            return base.Channel.GetFormations();
        }
        
        public bool TeamExists(string strTeamName) {
            return base.Channel.TeamExists(strTeamName);
        }
        
        public System.Data.DataTable GetAllCycles() {
            return base.Channel.GetAllCycles();
        }
        
        public int GetNumOfCycles() {
            return base.Channel.GetNumOfCycles();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MtaAddIn.localhost.GetGameStoryWithStringID1 MtaAddIn.localhost.GameSoap.GetGameStory(MtaAddIn.localhost.GetGameStoryWithStringID request) {
            return base.Channel.GetGameStory(request);
        }
        
        public MtaAddIn.localhost.GameStory GetGameStory(string strGameID) {
            MtaAddIn.localhost.GetGameStoryWithStringID inValue = new MtaAddIn.localhost.GetGameStoryWithStringID();
            inValue.strGameID = strGameID;
            MtaAddIn.localhost.GetGameStoryWithStringID1 retVal = ((MtaAddIn.localhost.GameSoap)(this)).GetGameStory(inValue);
            return retVal.GetGameStoryWithStringIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MtaAddIn.localhost.GetGameStoryWithIntegerID1 MtaAddIn.localhost.GameSoap.GetGameStory1(MtaAddIn.localhost.GetGameStoryWithIntegerID request) {
            return base.Channel.GetGameStory1(request);
        }
        
        public MtaAddIn.localhost.GameStory GetGameStory1(int nGameToShow) {
            MtaAddIn.localhost.GetGameStoryWithIntegerID inValue = new MtaAddIn.localhost.GetGameStoryWithIntegerID();
            inValue.nGameToShow = nGameToShow;
            MtaAddIn.localhost.GetGameStoryWithIntegerID1 retVal = ((MtaAddIn.localhost.GameSoap)(this)).GetGameStory1(inValue);
            return retVal.GetGameStoryWithIntegerIDResult;
        }
        
        public bool UserExists(string strUsername) {
            return base.Channel.UserExists(strUsername);
        }
        
        public Player[] GetPlayerNotForSell(MtaAddIn.localhost.Team tMyTeam) {
            return base.Channel.GetPlayerNotForSell(tMyTeam);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MtaAddIn.localhost.GetPlayerForSellWithTeamObject1 MtaAddIn.localhost.GameSoap.GetPlayerForSell(MtaAddIn.localhost.GetPlayerForSellWithTeamObject request) {
            return base.Channel.GetPlayerForSell(request);
        }
        
        public Player[] GetPlayerForSell(MtaAddIn.localhost.Team tMyTeam) {
            MtaAddIn.localhost.GetPlayerForSellWithTeamObject inValue = new MtaAddIn.localhost.GetPlayerForSellWithTeamObject();
            inValue.tMyTeam = tMyTeam;
            MtaAddIn.localhost.GetPlayerForSellWithTeamObject1 retVal = ((MtaAddIn.localhost.GameSoap)(this)).GetPlayerForSell(inValue);
            return retVal.GetPlayerForSellWithTeamObjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MtaAddIn.localhost.GetPlayerForSellWithTeamName1 MtaAddIn.localhost.GameSoap.GetPlayerForSell1(MtaAddIn.localhost.GetPlayerForSellWithTeamName request) {
            return base.Channel.GetPlayerForSell1(request);
        }
        
        public System.Data.DataTable GetPlayerForSell1(string strMyTeam) {
            MtaAddIn.localhost.GetPlayerForSellWithTeamName inValue = new MtaAddIn.localhost.GetPlayerForSellWithTeamName();
            inValue.strMyTeam = strMyTeam;
            MtaAddIn.localhost.GetPlayerForSellWithTeamName1 retVal = ((MtaAddIn.localhost.GameSoap)(this)).GetPlayerForSell1(inValue);
            return retVal.GetPlayerForSellWithTeamNameResult;
        }
        
        public bool CanISellPlayer(string iD) {
            return base.Channel.CanISellPlayer(iD);
        }
        
        public void UpdateSellPlayer(string strPlayerId, int intCost) {
            base.Channel.UpdateSellPlayer(strPlayerId, intCost);
        }
        
        public void CreateNewLeague() {
            base.Channel.CreateNewLeague();
        }
        
        public void DeleteLeague() {
            base.Channel.DeleteLeague();
        }
        
        public void CreateComputerTeam() {
            base.Channel.CreateComputerTeam();
        }
        
        public bool DoesComputerTeamExist() {
            return base.Channel.DoesComputerTeamExist();
        }
        
        public void DeleteComputerTeam() {
            base.Channel.DeleteComputerTeam();
        }
    }
}
